/*
  ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
  บ       ’   "T O P   S O F T",  €    "       € ’  €  ’"     บ
  บ      เฎฅชโ    : €€’€  (แ) 2000                                บ
  บ      ‘จแโฅฌ    : “ฏเ ขซฅญจฅ ฏฅเแฎญ ซฎฌ                              บ
  บ      ฅเแจ๏    : 5.8                                                บ
  บ       งเ กฎโ ซ: €ญโฎญฎขจ็ €..     02/08/2001                      บ
  บ       งญ ็ฅญจฅ: ’เใคฎขฎฉ คฎฃฎขฎเ ฏฎ ไฎเฌฅ ’D-1 ฏเจช ง ü 136        บ
  บ      งฌฅญฅญจ๏ :                                                    บ
  ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/

#doc
’เใคฎขฎฉ คฎฃฎขฎเ ฏฎ ไฎเฌฅ ’D-1 ฏเจช ง ü 136
#end
.form td_1_136
.Hide
.Fields

KatOrg_Name
KatOrg_OKPO
INN
KatOrg_Name_short
Org_JuridicalAddress
NRecApp
Num_Doc
Date_Doc
BossPost
BossFIO
NRecPsn
FIO
FIO_VP
AppPostCat_Name
KlKatego_NaiKat
AppKatPodr_Name
AppointDate
DateEnd
KlSovm_NSovm

TestPeriodMes
TestPeriodDn

JobNature
PostAddress

dat1_1
dat1_2
dat1_3

topKoef

Raise_nrec
Raise_from
Raise_to
dat2_1
dat2_2
dat2_3

dat3

usl_1
usl_2
usl_3
usl_4

ind1
ind2
adr1
adr2_1
tel_1
adr2_2
rekvOrg1
tel_2
rekvOrg2
PasspSer
PasspNum
rekvOrg3
rekvOrg4
PaspDate
PaspDateStr
Post
FIO1
ContractNmb
ContractDate
FIO2

.endFields

KatOrg_Name              ^
KatOrg_OKPO              ^
INN                      ^
KatOrg_Name_short        ^
Org_JuridicalAddress     ^
NRecApp                  ^
Num_Doc                  ^
Date_Doc                 ^
BossPost                 ^
BossFIO                  ^
NRecPsn                  ^
FIO                      ^
FIO_VP                   ^
AppPostCat_Name          ^
KlKatego_NaiKat          ^
AppKatPodr_Name          ^
AppointDate              ^
DateEnd                  ^
KlSovm_NSovm             ^

TestPeriodMes            ^
TestPeriodDn             ^

JobNature                ^
PostAddress              ^

dat1_1                   ^
dat1_2                   ^
dat1_3                   ^

topKoef                  ^


.{ Td_1_136_Cycle1 CheckEnter
Raise_nrec               ^
Raise_from               ^
Raise_to                 ^
dat2_1                   ^
dat2_2                   ^
dat2_3                   ^
.}

dat3                     ^

usl_1                    ^
usl_2                    ^
usl_3                    ^
usl_4                    ^

ind1                     ^
ind2                     ^
adr1                     ^
adr2_1                   ^
tel_1                    ^
adr2_2                   ^
rekvOrg1                 ^
tel_2                    ^
rekvOrg2                 ^
PasspSer                 ^
PasspNum                 ^
rekvOrg3                 ^
rekvOrg4                 ^
PaspDate                 ^
PaspDateStr              ^
Post                     ^
FIO1                     ^
ContractNmb              ^
ContractDate             ^
FIO2                     ^

.endform
