#define mycDopTblDover 4
#define mycDolKadrBoss 'Начальник отдела кадров'
#define mycNameKadrBoss 'М.Ф. Кузнецова'
#define mycDolOTIZBOss 'Начальник ОТиЗ'
#define mycNameOTIZBoss 'Инициалы и Фамилия'
#define myCodeKauObjStroy 40
#define myCodeKauRBP 10063
#define coSch07 7
#define coSch10 9
#define coSch002 11
#define coSch005 13
Const
  myCatCodeSokSht = '81_пункт_2';
  myCatCodeNar1 = '81_пункт_6_подп.а)';
  myCatCodeNar2 = '81_пункт_6_подп.б)';
  myCatCodeNar3 = '81_пункт_6_подп.в)';
  myCatCodeNar4 = '81_пункт_6_подп.г)';
  myCatCodeNar5 = '81_пункт_6_подп.д)';
  myCatCodeWish = '77';
  myCatCodeEndTruDog = '77_пункт_2';
  myPodrAUPCode = '01';
  myPodrJARNUCode = '03';
  myPodrVRNUCode = '02';
  myPodrBPTOCode = '04';
  myPodrSBCode = '01358';
  mycBankPathAUP1='Z:\sbersign\';
  mycBankPathVRNU1='c:\';
  mycBankPathYRNU1='c:\';
  mycSberPath='C:\sbersign\win\';
  myCodeKauObjStroy = 40;
  myCodeKauRBP = 10063;
  myCodeKauVidD = 20009;
  myCodeKauVidStrah = 10083;
  mycnsttnDATECLOSEPERIOD = 'OPER.DATECLOSEPERIOD';
  mycnsttnMODORDER = 'MCUSL.MODORDER';
  mycnsttnDTECBUH = 'FIN.USER.DTECBUH';
  mycnsttnMODAFTERCLOSE = 'FIN.USER.MODAFTERCLOSE';